services:
  dev-python313-ai-information-collection-app:
    container_name: ${APP_NAME}
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile.dev
    tty: true
    working_dir: /var/task
    volumes:
      - ../requirements.txt:/var/task/requirements.txt
      - ../requirements-dev.txt:/var/task/requirements-dev.txt
      - ../src:/var/task/src
      - ../tests:/var/task/tests
    env_file:
      - ../.env
