FROM public.ecr.aws/lambda/python:3.13

WORKDIR ${LAMBDA_TASK_ROOT}

RUN dnf install -y tar gzip git
RUN pip install pdm

COPY pyproject.toml ./
COPY pdm.lock ./

RUN pdm install --global --project .

CMD [ "bash" ]