FROM public.ecr.aws/lambda/python:3.13

RUN dnf install -y tar gzip git

COPY requirements.txt ${LAMBDA_TASK_ROOT}
RUN pip install -r requirements.txt
COPY requirements-dev.txt ${LAMBDA_TASK_ROOT}
RUN pip install -r requirements-dev.txt

CMD [ "bash" ]