services:
  dev-python313-ai-information-collection-app:
    container_name: ${APP_NAME}
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile.dev
    tty: true
    working_dir: /var/task
    volumes:
      - ../pyproject.toml:/var/task/pyproject.toml
      - ../pdm.lock:/var/task/pdm.lock
      - ../src:/var/task/src
      - ../tests:/var/task/tests
      - ../.vscode:/var/task/.vscode
    env_file:
      - ../.env
