FROM public.ecr.aws/lambda/python:3.13

RUN dnf install -y tar gzip git
RUN pip install pdm

COPY pyproject.toml ${LAMBDA_TASK_ROOT}
COPY pdm.lock ${LAMBDA_TASK_ROOT}

RUN pdm install --global --project .

CMD [ "bash" ]